# Generated by Django 4.2.2 on 2023-07-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='github',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
