# Generated by Django 4.2.2 on 2023-07-01 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_site', '0002_work_github'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploadresume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='images/')),
            ],
        ),
    ]
